version: '3'
services:
  selenium-hub-b2b:
    image: selenium/hub:4.1.0
    container_name: selenium-hub-b2b
    ports:
      - 7000:4442
      - 7001:4443
      - 7002:4444

  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: 2gb
    depends_on:
      - selenium-hub-b2b
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-b2b
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - START_XVFB=false
    volumes:
      - ".:/home/seluser/Downloads"

  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: 2gb
    depends_on:
      - selenium-hub-b2b
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-b2b
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - START_XVFB=false
    volumes:
      - ".:/home/seluser/Downloads"
